name: CI - Go Inventory App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Instalar dependencias
        run: go mod tidy

      - name: Ejecutar pruebas
        run: |
          go test ./tests/... -v
          echo "✅ DEPLOYMENT APPROVED - ALL TESTS SUCCESSFUL!"
